client:
  needs: server
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: [3.10]  # Ensure this is a valid Python version
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      working-directory: ./client
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

